name: deployEC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ "closed" ]

  workflow_dispatch:

jobs:
  build:
    #if_merged:
      #if: github.event.pull_request.merged == true
    name: "Terraform build"
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Apply
        run: |
          cd terraform/
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
