name: deployEC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ "closed" ]

  workflow_dispatch:

jobs:
  build:
    if_merged:
      if: github.event.pull_request.merged == true
      name: "Terraform build"
      runs-on: ubuntu-latest

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'

      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout
          uses: actions/checkout@v4
      
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2

        - name: Terraform Apply
          run:
            cd terraform/ 
            terraform init
            terraform validate
            terraform plan -auto-approve
            terraform apply -auto-approve

